version: "3"
services:
  mysql:
    image: "mysql:latest"
    container_name: mysql-nestjs
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=orders
    ports:
      - "3307:3306"
    volumes:
      - ".docker/mysql:/var/lib/mysql"